### ISSUE TITLE
Enhancement - move divs / columns

### ISSUE THREAD

**Issue by coconnor999** [updrafts/public#5]
Almost a deal breaker for the tool - need to be able to move divs / columns / sections after placed.  Alternative would be to directly edit the HTML, but that doesn't seem to be possible either.

**Comment by smeijer** [comment]
It is possible to drag and rearrange elements by using the navigator. Dragging on the canvas will be included in later version.

**Comment by coconnor999** [comment]
Thank you, great to know but not quite workable once you have nested divs -
most of the blocks I want to move don't show up on the Navigator view:

[image: image.png]

**Comment by smeijer** [comment]
This will be part of the next release https://twitter.com/meijer_s/status/1343884295027511296?s=19

**Comment by smeijer** [comment]
This is now supported.

https://twitter.com/meijer_s/status/1345765306069880832?s=19
